### ISSUE TITLE
Cleanup deployment template in chart

### ISSUE THREAD

**Issue by hawksight** [jetstack/version-checker#187]
For example, remove comments and blank lines:

```yaml
# Source: version-checker/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-checker
  labels:

    app.kubernetes.io/name: version-checker
    helm.sh/chart: version-checker-v0.5.4
    app.kubernetes.io/instance: version-checker
    app.kubernetes.io/version: "v0.5.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: version-checker
      app.kubernetes.io/instance: version-checker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: version-checker
        helm.sh/chart: version-checker-v0.5.4
        app.kubernetes.io/instance: version-checker
        app.kubernetes.io/version: "v0.5.4"
        app.kubernetes.io/managed-by: Helm
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        enable.version-checker.io/version-checker: "true"
    spec:
      serviceAccountName: version-checker
      containers:
      - name: version-checker
        image: "quay.io/jetstack/version-checker:v0.5.4"
        imagePullPolicy: IfNotPresent
        ports:
        - name: metrics
          containerPort: 8080
        command: ["version-checker"]
        args:
          - "--image-cache-timeout=30m"
          - "--log-level=info"
          - "--metrics-serving-address=0.0.0.0:8080"
          - "--test-all-containers=true"
        resources:
            {}
        livenessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        # ACR

        # ECR

        # Docker

        # GCR

        # GHCR

        # Quay

        # Selfhosted


      volumes:

```
