### ISSUE TITLE
Fails on registry.opensource.zalan.do/teapot/external-dns

### ISSUE THREAD

**Issue by MPV** [jetstack/version-checker#53]
Enabled this for the `external-dns` helm-chart, but it fails with:

`time="2020-10-01T12:13:14Z" level=error msg="error syncing 'external-dns-87d6cdc68-z9fdn/external-dns': failed to sync pod external-dns-87d6cdc68-z9fdn/external-dns: failed to check container image \"external-dns\": failed to get tags from remote registry for \"registry.opensource.zalan.do/teapot/external-dns\": failed to get docker image: Get \"https:///v2/teapot/external-dns/tags/list?n=500\": http: no Host in request URL, requeuing" module=controller`

**Comment by JoshVanL** [comment]
Thanks @MPV, it looks like I can preliminarily reproduce the issue. As a work around, can you try to define a selfhosted registry for this host?

```
selfhosted:
  - name: ZALAN
    host: https://registry.opensource.zalan.do
    username:
    password:
    token:
```

I would expected this to work out the box, and is a bug.

/assign
/kind bug
