### ISSUE TITLE
override-url does not seem to work

### ISSUE THREAD

**Issue by yogeek** [jetstack/version-checker#64]
Hello,

I deployed version-checker with `testAllContainers: true` and try to override the registry for one of my image using the annotation : 

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    override-url.version-checker.io/frontend: gcr.io/google-samples/microservices-demo/frontend
[...]
spec:
  containers:
    image: XXXX.dkr.ecr.eu-central-1.amazonaws.com/google-samples/microservices-demo/frontend:v0.2.1
[...]
```

but the url is not overriden :

```
$ stern version -n version-checker | grep frontend

version-checker-58f996cdc5-tfffj version-checker time="2020-11-20T18:30:47Z" level=error msg="error syncing 'frontend-5c88f5f675-wccfx/microdemo': failed to sync pod frontend-5c88f5f675-wccfx/microdemo: failed to check container image \"server\": failed to get tags from remote registry for \"XXXX.dkr.ecr.eu-central-1.amazonaws.com/google-samples/microservices-demo/frontend\": failed to describe images: EmptyStaticCreds: static credentials are empty, requeuing" module=controller
```
